### ISSUE TITLE
Check Orders doesn't work properly on Mac

### ISSUE THREAD

**Issue by ravenzachary** [JOverseer/joverseer#677]
For some reason, when running Check Orders on the Mac, it's not flagging double character order conflicts (hiring army and hiring commander on the same turn, for instance) the way it does on PC. I am running the latest public version, and this has been a problem since at least late March 2018 when I started playing MEPBM again.

**Comment by GnarlyDave** [comment]
It's not as simple as that...I looks like the check for using a second skill order is one of the last to be done, so if anything else is wrong before that, then the check is skipped. I've seen, and corrected some silent exceptions that do this, so unfortunately, it needs tracking down on a case by case basis.

**Comment by ravenzachary** [comment]
Dave - how would you like me to re-open this ticket so that I can get order checking to work? It does not catch double skill orders on my computer in any condition. I've never once seen it work. I would love to get this fixed.

**Comment by GnarlyDave** [comment]
reopened and I've sent you an email.

**Comment by GnarlyDave** [comment]
ah, a comment in the rules.csv file for orderchecker:

# Checks NOT performed since Automagic/MEOW does them - but these are gone and Joverseer needs to pick up that job
# Capital check
# 2 Orders from same skill
# Comm/Em/Agent/Mage skill requirement for an order.,,

What's also confusing, and explains why it hasn't been noticed much, is that JO (rather than orderchecker) has a separate lightweight order validation mechanism, which is visible on the Current Hex View and influences the yellow background of cells in the Order List View. It does show skill requirements and duplicate skill orders.

Also the results from running orderchecker, were a bit lazy in appearing on the Order List View - OC results column which I've fixed for 1.16.11 when it appears.

I've worked out how to extend orderchecker for skill requirements and duplicate skill checks, and I'm testing that. It might be a while before that appears.

**Comment by GnarlyDave** [comment]
1.16.11 is out.
Some skill orders are checked for duplicate skill. I'm just lacking time to do more at the moment.
In the ruleset.csv file, the RANK command now has two extra optional parameters, onlyone, and capital respectively. If onlyone is true, then it expects only one of that skill type allowed for a character. If capital is true, then the character must also be at the capital.
