### ISSUE TITLE
Change Allegiance (175) causes Order Checker to always fail

### ISSUE THREAD

**Issue by ravenzachary** [JOverseer/joverseer#699]
If you have a 175 order, and use Order Checker, you will always receive this error message:

![Screen Shot 2020-05-01 at 14 13 59](https://user-images.githubusercontent.com/645975/80842326-289e6780-8bb6-11ea-825f-18068bcaa746.png)

JOverseer v1.16.17 on Mac OS X 10.15.4

**Comment by GnarlyDave** [comment]
This is a data format problem in orderchecker's list of rules for order 175.
This means the data for the RANK rule has the wrong number of parameters.
Some rules are using a slightly different format for the RANK rule, putting the RANK rule in the same line as the order.
In the past the RANK order was enhanced to check for a capital requirement and exclusive order requirement.
fixed in 1.16.18
